name = "contact-worker"
main = "src/index.ts"
compatibility_date = "2023-12-01" # Or a recent date

[vars]
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN_SECRET"
MY_CHAT_ID = "YOUR_TELEGRAM_CHAT_ID_SECRET"
